apiVersion: v1
data:
  logback.xml: |
    <configuration>
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            </encoder>
        </appender>

        <root level="debug">
            <appender-ref ref="STDOUT" />
        </root>
    </configuration>
kind: ConfigMap
metadata:
  name: apresentacao-backend-logback-config-map
  labels:
    app: apresentacao-backend
