kind: Service
apiVersion: v1
metadata:
  labels:
    app: apresentacao-backend
  name: service-apresentacao-backend
spec:
  selector:
    app: apresentacao-backend
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080